# Generated by Django 4.2.1 on 2023-06-05 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('discription', models.CharField(max_length=500, verbose_name='Descrição')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Ultima alteração')),
                ('delete_on_reset_day', models.BooleanField(verbose_name='Deletar no dia de exclusão')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dono')),
                ('photos', models.ManyToManyField(blank=True, null=True, to='photos.photo', verbose_name='Fotos')),
                ('shared_with', models.ManyToManyField(related_name='album_shared_with', to=settings.AUTH_USER_MODEL, verbose_name='Compartilhado com')),
            ],
        ),
    ]
