# Generated by Django 4.2.1 on 2023-07-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0002_alter_album_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Capa'),
        ),
    ]
