# Generated by Django 4.2.1 on 2023-07-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0003_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(upload_to='', verbose_name='Capa'),
        ),
    ]
