# Generated by Django 4.2.1 on 2023-07-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_remove_photo_shared_with'),
        ('albuns', '0005_alter_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(to='photos.photo', verbose_name='Fotos'),
        ),
    ]
