# Generated by Django 4.2.1 on 2023-07-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0006_alter_album_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='delete_on_reset_day',
            field=models.BooleanField(default=False, verbose_name='Deletar no dia de exclusão'),
        ),
    ]
