# Generated by Django 4.2.1 on 2023-07-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_photo'),
        ('albuns', '0007_alter_album_delete_on_reset_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='photos.photo', verbose_name='Fotos'),
        ),
    ]
