# Generated by Django 4.2.1 on 2023-06-07 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='shared_with',
        ),
    ]
