# Generated by Django 4.2.1 on 2023-07-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_remove_photo_shared_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=8050, null=True, verbose_name='Titulo'),
        ),
    ]
