# Generated by Django 4.2.1 on 2023-07-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='discription',
            new_name='drive_id',
        ),
    ]
